//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int PY__Id { get; set; }
        public string PY_Name { get; set; }
        public int P_Id { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
